services:
  web:
    image: php:8.4-apache
    environment:
      - APP_ENV=development
      - DEBUG_MODE=1
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=mydb
    container_name: CoJevBrode
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.3
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
    ports:
      - "8306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
